---
- name: Install addons
  command: kubectl apply -f /vagrant/addons/files/{{ item }}.yaml
  loop:
  - nginx-ingress-controller-1.3
  - local-path-storage
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: Set local path provisioner as default storage class
  lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    regexp: '- --enable-admission-plugins=NodeRestriction'
    line: '    - --enable-admission-plugins=NodeRestriction,DefaultStorageClass'
    state: present

  # https://kubernetes.io/docs/reference/using-api/health-checks/#api-endpoints-for-health
- name: Wait for API Server to be ready after changes were made
  uri:
    url: https://localhost:6443/livez?verbose
    validate_certs: false
  register: result
  retries: 12
  delay: 10
  until: result.status == 200

- name: Patch Storage Class for local path provisioner
  command: | 
    kubectl patch sc local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"